movie_store/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from django.contrib import admin


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^movies/', include('movies.urls')),
	url(r'^', RedirectView.as_view(url=reverse_lazy('movie_list'))),
)

movies/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import ListView, DetailView
from movies.models import Genre, Movie, Studio


urlpatterns = patterns('',
  url('^genres/(?P<slug>[-\w]+)/$', DetailView.as_view(model=Genre),name='movie_genre_detail'),
  url ('^genres/$', ListView.as_view(model=Genre),name='movie_genre_list'),
  url('^studios/(?P<slug>[-\w]+)/$', DetailView.as_view(model=Studio), name='movie_studio_detail'),
  url ('^studios/$',ListView.as_view(model=Studio),name='movie_studio_list'),
  url('^(?P<slug>[-\w]+)/$', DetailView.as_view(model=Movie),name='movie_detail'),
  url ('^$',ListView.as_view(model=Movie),name='movie_list'),
)

movies/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings


class Genre(models.Model):
  """ Genre model """
  title         = models.CharField(max_length=100)
  slug          = models.SlugField(unique=True)
  
  class Meta:
    db_table = 'movie_genres'
    ordering = ('title',)

  def __unicode__(self):
    return '%s' % self.title
  
  @permalink
  def get_absolute_url(self):
    return ('movie_genre_detail', None, { 'slug': self.slug })


class Studio(models.Model):
  """ Studio model """
  title         = models.CharField(max_length=100)
  prefix        = models.CharField(max_length=20, blank=True)
  slug          = models.SlugField(unique=True)
  website       = models.URLField(blank=True)

  class Meta:
    db_table = 'movie_studios'
    ordering = ('title',)

  def __unicode__(self):
    return '%s' % self.full_title

  @property
  def full_title(self):
    return '%s %s' % (self.prefix, self.title)

  @permalink
  def get_absolute_url(self):
    return ('movie_studio_detail', None, { 'slug': self.slug })
    
    
class Movie(models.Model):
  """ Movie model """
  title         = models.CharField(max_length=255)
  prefix        = models.CharField(max_length=20, blank=True)
  subtitle      = models.CharField(blank=True, max_length=255)
  studio        = models.ForeignKey(Studio, blank=True, null=True)
  slug          = models.SlugField(unique=True)
  released      = models.DateField(blank=True, null=True)
  asin          = models.CharField(blank=True, max_length=100)
  cover         = models.FileField(upload_to='films', blank=True)
  review        = models.TextField(blank=True)
  genre         = models.ManyToManyField(Genre, blank=True)

  class Meta:
    db_table = 'movies'
    ordering = ('title',)

  def __unicode__(self):
    return '%s' % self.full_title
  
  @property
  def full_title(self):
    return '%s %s' % (self.prefix, self.title)
    
  @property
  def cover_url(self):
    return '%s%s' % (settings.MEDIA_URL, self.cover)
  
  @permalink
  def get_absolute_url(self):
    return ('movie_detail', None, { 'slug': self.slug })

movies/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{% block title %}{% endblock %}</title>
	<meta name="author" content="Nathan Borror">
</head>
<body id="{% block body_id %}{% endblock %}">
  <div id="body">
    {% block body %}
      <div>
        {% block content_title %}{% endblock %}
      </div>
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
  </div>
</body>
</html>

movies/templates/movies/_nav.html
<div id="section_nav">
  <ul>
    <li class="movies"><a href="{% url 'movie_list' %}">Movies</a>
      <ul>
        <li class="genres"><a href="{% url 'movie_genre_list' %}">Genres</a></li>
      <li class="studios"><a href="{% url 'movie_studio_list' %}">Studios</a></li>
      </ul>
    </li>
  </ul>
</div>

movies/templates/movies/base_movies.html
{% extends "base.html" %}


{% block body_class %}movies{% endblock %}

movies/templates/movies/genre_detail.html
{% extends "movies/base_movies.html" %}


{% block title %}{{ object.title }}{% endblock %}
{% block body_class %}{{ block.super }} movie_genres{% endblock %}


{% block content_title %}
  <h2>Movie Genres</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.title }}</h4>
  <ul class="link_list">
    {% for movie in object.movie_set.all %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

movies/templates/movies/genre_list.html
{% extends "movies/base_movies.html" %}


{% block title %}Movie Genres{% endblock %}
{% block body_class %}{{ block.super }} movie_genres{% endblock %}


{% block content_title %}
  <h2>Movie Genres</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for genre in object_list %}
    <li><a href="{{ genre.get_absolute_url }}">{{ genre.title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends "movies/base_movies.html" %}


{% block title %}{{ object.full_title }}{% endblock %}


{% block content_title %}
  <h2>Movies</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  {% load markup %}
  <h3>{{ object.full_title }}
  {% if object.subtitle %}<em>{{ object.subtitle }}</em></h3>{% endif %}
  
  {% if object.cover %}
  <a class="cover" href="{{ object.amazon_url }}"><img src="{{ object.cover_url }}" alt="Movie cover"></a>
  {% else %}
  <div class="no_cover"></div>
  {% endif %}
  
  <ul class="info_list">
    <li>Directors: {% for director in object.directors.all %}<a href="{{ director.get_absolute_url }}">{{ director.full_name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>Studio: <a href="{{ object.studio.get_absolute_url }}">{{ object.studio.full_title }}</a></li>
    <li>Released: {{ object.released|date:"d F Y" }}</li>
    <li>Genre: {% for genre in object.genre.all %}{{ genre.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>ASIN: {{ object.asin }} (<a href="{{ object.amazon_url }}">Amazon</a>)</li>
  </ul>
  
  {% if object.review %}
  <div class="review">
    <h4>Review</h4>
    {{ object.review|markdown }}
  </div>
  {% endif %}
{% endblock %}

movies/templates/movies/movie_list.html
{% extends "movies/base_movies.html" %}


{% block title %}Movies{% endblock %}


{% block content_title %}
  <h2>Movies</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for movie in object_list %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

movies/templates/movies/studio_detail.html
{% extends "movies/base_movies.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} movie_studios{% endblock %}


{% block content_title %}
  <h2>Movie Studios</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.full_title }}</h3>
  <ul class="link_list">
    {% for movie in object.movie_set.all %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

movies/templates/movies/studio_list.html
{% extends "movies/base_movies.html" %}


{% block title %}Movie Studios{% endblock %}
{% block body_class %}{{ block.super }} movie_studios{% endblock %}


{% block content_title %}
  <h2>Movie Studios</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for studio in object_list %}
    <li><a href="{{ studio.get_absolute_url }}">{{ studio.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}